openapi: 3.0.3
info:
  version: 1.0.0
  title: Base Fiber API
  description: 'This is a simple acl API built with Fiber'
  contact:
    name: Maia
    email: gabrielmaialva33@gmail.com
    url: github.com/gabrielmaialva33
servers:
  - url: http://127.0.0.1:3333
paths:
  /signin:
    post:
      tags:
        - User
      summary: Sign In
      description: 'Sign in user into the system'
      operationId: SignInUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignIn'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignInSuccess'
        '400':
          description: Bad request response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableEntity'
  /signup:
    post:
      tags:
        - User
      summary: SignUp
      description: 'Sign up user into the system'
      operationId: SignUpUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUp'
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignInSuccess'
        '400':
          description: Bad request response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableEntity'

  # authorization routes
  /users:
    get:
      tags:
        - User
      summary: List users
      description: 'Get all users from the system'
      operationId: ListUsers
      parameters:
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 100
            default: 1
        - name: per_page
          in: query
          description: Number of users per page
          required: false
          schema:
            type: integer
            format: int32
            default: 10
            minimum: 1
        - name: search
          in: query
          description: Search by public user attributes
          required: false
          schema:
            type: string
            default: 'first_name'
        - name: sort
          in: query
          description: Sort by public user attributes
          required: false
          schema:
            type: string
            default: 'id'
        - name: order
          in: query
          description: Order by public user attributes
          required: false
          schema:
            type: string
            default: 'asc'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListUsers'
        '400':
          description: Bad request response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
    post:
      tags:
        - User
      summary: Store user
      description: 'Store user into the system'
      operationId: StoreUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUp'
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicUser'
        '400':
          description: Bad request response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableEntity'
  /users/{id}:
    get:
      tags:
        - User
      summary: Get user
      description: 'Get user by id'
      operationId: GetUser
      parameters:
        - name: id
          in: path
          description: User id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicUser'
        '400':
          description: Bad request response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
    put:
        tags:
          - User
        summary: Edit user
        description: 'Edit user by id'
        operationId: EditUser
        parameters:
            - name: id
              in: path
              description: User id
              required: true
              schema:
                type: string
                format: uuid
        requestBody:
          required: true
          content:
           application/json:
            schema:
             $ref: '#/components/schemas/PublicUser'
        responses:
            '200':
              description: successful operation
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/PublicUser'
            '400':
              description: Bad request response
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/BadRequest'
            '404':
              description: User not found
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/NotFound'
            '422':
              description: Unprocessable Entity
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/UnprocessableEntity'

tags:
  - name: User
    description: Operations about user
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    '200':
      description: OK
    '401':
      description: Unauthorized
    '422':
      description: Unprocessable Entity
    '404':
      description: Not Found
  schemas:
    # Entities
    PublicUser:
      type: object
      properties:
        id:
          type: string
          format: uuid
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        user_name:
          type: string

    # Request Body Schemas
    SignIn:
      type: object
      properties:
        uid:
          type: string
        password:
          type: string
      example:
        uid: root
        password: '123456'
    SignUp:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        user_name:
          type: string
        password:
          type: string
        confirm_password:
          type: string
      example:
        first_name: John
        last_name: Doe
        email: john@email.com
        user_name: john
        password: password
        confirm_password: password

    # Responses Schemas
    Meta:
      type: object
      properties:
        total:
          type: number
          format: int64
        total_pages:
          type: number
          format: int64
        per_page:
          type: number
          format: int64
        current_page:
          type: number
          format: int64
        search:
          type: string
        sort:
          type: string
        order:
          type: string
      example:
        total: 1
        total_pages: 1
        per_page: 10
        current_page: 1
        search: ''
        sort: 'id'
        order: 'asc'

    ListUsers:
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/Meta'
        data:
          type: array
          items:
            $ref: '#/components/schemas/PublicUser'

    # Success Responses
    SignInSuccess:
      type: object
      properties:
        message:
          type: string
        status:
          type: number
          format: int64
        display:
          type: boolean
        user:
          $ref: '#/components/schemas/PublicUser'
        token:
          type: string
      example:
        display: false
        message: Login successful
        status: 200
        token: token here
        user:
          id: 93d7ad22-87e0-41b4-8b90-745bd87fa9af
          first_name: John
          last_name: Doe
          email: john@email.com
          user_name: john

    # Errors Responses
    NotFound:
      type: object
      properties:
        message:
          type: string
        status:
          type: number
          format: int64
        error:
          type: string
        display:
          type: boolean
      example:
        message: "User not found"
        status: 404
        error: "record not found"
        display: true
    BadRequest:
      type: object
      properties:
        message:
          type: string
        status:
          type: number
          format: int64
        error:
          type: string
        display:
          type: boolean
      example:
        message: "Error while parsing data"
        status: 400
        error: "invalid character '}' looking for beginning of object key string"
        display: false
    Unauthorized:
      type: object
      properties:
        message:
          type: string
        status:
          type: number
          format: int64
        display:
          type: boolean
      example:
        message: "Invalid credentials"
        status: 401
        display: true
    UnprocessableEntity:
      type: object
      properties:
        message:
          type: string
        status:
          type: number
          format: int64
        errors:
          type: array
          items:
            type: object
            properties:
              failed_field:
                type: string
              tag:
                type: string
              field:
                type: string
              value:
                type: string
              param:
                type: string
              message:
                type: string
        display:
          type: boolean
      example:
        message: "Validation failed"
        status: 422
        errors:
          - failed_field: "email"
            tag: "email"
            field: "email"
            value: "john@email"
            param: ""
            message: "email must be a valid email"
        display: true




